Changed Homework-L21
FE38-Front-End/ViktorGubarevich pull request #6
Opened 2020-11-30 19:50 UTC by ViktorGubarevich

Homework-L21.

2020-12-07 10:07 UTC, akhovbok requested changes

2020-12-07 10:07 UTC, akhovbok commented on Homework-L21/app/script-task-first.js
> +const text = document.querySelector('ul').textContent;
хочу проход по отдельной li

2020-12-07 10:07 UTC, akhovbok commented on Homework-L21/app/script-task-second.js
> +    const scroll = document.createElement('li');
почему scroll?

2020-12-07 10:07 UTC, akhovbok commented on Homework-L21/app/script-task-second.js
> +const fragment = document.createDocumentFragment();
+

2020-12-08 12:22 UTC, ViktorGubarevich commented on Homework-L21/app/script-task-second.js
> +    const scroll = document.createElement('li');
Внес изменения.

2020-12-08 12:31 UTC, ViktorGubarevich commented on Homework-L21/app/script-task-first.js
> +const text = document.querySelector('ul').textContent;
Исправлено.

2020-12-08 12:32 UTC, merged