Homework/Classwork-L22
FE38-Front-End/ViktorGubarevich pull request #7
Opened 2020-12-02 19:39 UTC by ViktorGubarevich

Homework/Classwork-L22.

2020-12-03 12:03 UTC, akhovbok requested changes

2020-12-03 12:03 UTC, akhovbok commented on Homework:Classwork-L22/app/script.js
> +
лишний отступ

2020-12-03 12:03 UTC, akhovbok commented on Homework:Classwork-L22/app/script.js
> +
два лишних отступа

2020-12-03 12:03 UTC, akhovbok commented on Homework:Classwork-L22/app/script.js
> +        return;
код написан не в одной стилистике

2020-12-08 13:34 UTC, ViktorGubarevich commented on Homework:Classwork-L22/app/script.js
> +        return;
Исправлено.

2020-12-08 13:35 UTC, merged